### ISSUE TITLE
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.

### ISSUE THREAD

**Issue by Wolfteam** [AndreiMisiukevich/CardView#194]
Hi, thanks for your awesome lib /,,,/.

Im trying to achieve a layout like the following :
![Untitled](https://user-images.githubusercontent.com/1976115/56435389-38e2ed80-62a6-11e9-8139-13b62763acee.png)

In the image the oval represents the `CarouselView`.
I'm using the visual state manager to change the position of the items when the device rotates and everything seems to work except that i get the following exception when there are 2 or more items in the ``CarouselView.ItemsSource`` property and the orientation change happens from Landscape to Portrait
````
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRange_IndexException()
   at Xamarin.Forms.Grid.LayoutChildren(Double x, Double y, Double width, Double height)
   at Xamarin.Forms.Layout.UpdateChildrenLayout()
   at Xamarin.Forms.VisualElement.SetSize(Double width, Double height)
   at Xamarin.Forms.VisualElement.set_Bounds(Rectangle value)
   at Xamarin.Forms.Layout.LayoutChildIntoBoundingRegion(VisualElement child, Rectangle region)
   at Xamarin.Forms.Page.LayoutChildren(Double x, Double y, Double width, Double height)
   at Xamarin.Forms.Page.UpdateChildrenLayout()
   at TimeIt.MainPage.OnSizeAllocated(Double width, Double height)
   at Xamarin.Forms.VisualElement.SetSize(Double width, Double height)
   at Xamarin.Forms.VisualElement.set_Bounds(Rectangle value)
   at Xamarin.Forms.Layout.LayoutChildIntoBoundingRegion(VisualElement child, Rectangle region)
   at Xamarin.Forms.Page.LayoutChildren(Double x, Double y, Double width, Double height)
   at Xamarin.Forms.Page.UpdateChildrenLayout()
   at Xamarin.Forms.Platform.UWP.NavigationPageRenderer.UpdateContainerArea()
````

By looking at the stack trace, it looks like its a xf bug... but im not sure.. maybe i missed something?.
Im attaching a sample project, hope you can help me figure out the issue.
[FormsTesting.zip](https://github.com/AndreiMisiukevich/CardView/files/3098832/FormsTesting.zip)

**Comment by AndreiMisiukevich** [comment]
Hi, thank you very much for feedback.
Yes, from first sight it looks like XF bug indeed. But let me confirm it :)

**Comment by AndreiMisiukevich** [comment]
Added workaround for this issue

**Comment by AndreiMisiukevich** [comment]
v 2.0.9

**Comment by scteodor** [comment]
> Added workaround for this issue

Where?

**Comment by AndreiMisiukevich** [comment]
> > Added workaround for this issue
> 
> Where?

https://github.com/AndreiMisiukevich/CardView/commit/8e36b7e350d2da0871fa8ddd990c20b2f0b1489f

Seems this helped
