### ISSUE TITLE
Error after installing the Nuget (any version from 2.1.2 to 2.2.0)

### ISSUE THREAD

**Issue by dvirsf** [AndreiMisiukevich/CardView#254]
Hi,
when trying to rebuild the project (Android) right after installing the NuGet, I get the following erro - The "LinkAssemblies" task failed unexpectedly.
Mono.Linker.MarkException: Error processing method: 'Xamarin.Forms.Style PanCardView.Controls.Styles.DefaultIndicatorItemStyles::get_DefaultUnselectedIndicatorItemStyle()' in assembly: 'PanCardView.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve Xamarin.Forms.BindableProperty Xamarin.Forms.Frame::BorderColorProperty
   at Mono.Linker.Steps.MarkStep.HandleUnresolvedField(FieldReference reference)
   at Mono.Linker.Steps.MarkStep.MarkField(FieldReference reference)
   at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
   at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   --- End of inner exception stack trace ---
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
   at Mono.Linker.Steps.MarkStep.Process()
   at MonoDroid.Tuner.MonoDroidMarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	GameManager.Android			

I'm using VS 2019 with C#

**Comment by AndreiMisiukevich** [comment]
Do you use PCL or .netstandard?
What XF version do you use?

**Comment by dvirsf** [comment]
Hi,
XF version 4.2.0 and .NET standard.
Thanks

**Comment by AndreiMisiukevich** [comment]
@dvirsf did you call Preserve method as described in Readme?

**Comment by dvirsf** [comment]
Yes I did and the error is still there. Anyhow I don't think it should change anything, the error is during compilcation

**Comment by AndreiMisiukevich** [comment]
@dvirsf can you send me a sample? just create a new project and install this NuGet

**Comment by dvirsf** [comment]
Hi, 
my bad. It was late and I checked the wrong project :(. Its a PCL project not .net standard.

**Comment by AndreiMisiukevich** [comment]
@dvirsf PCL is not supported anymore. Not sure 2.1.4 probably latest version for PCL
