### ISSUE TITLE
Сhanging the list causes an error

### ISSUE THREAD

**Issue by JTOne123** [AndreiMisiukevich/CardView#36]
Steps to reproduce:
App has 2 screens and typical navigation

1. List with 2 items (in the cardview) on the first screen
2. Switch to the second item
3. Go to the second screen
4. Delete the second item
5. Back to the first screen
6. Set new data to cardview on appeared event
7. You'll get the exception

```
   at System.ThrowHelper.ThrowArgumentOutOfRange_IndexException()
   at System.Collections.Generic.List`1.System.Collections.IList.get_Item(Int32 index)
   at PanCardView.CardsView.GetContext(Int32 index, AnimationDirection animationDirection)
   at PanCardView.CardsView.PrepareView(Int32 index, AnimationDirection animationDirection, IEnumerable`1 bookedViews)
   at PanCardView.CardsView.GetViews(AnimationDirection animationDirection, ICardProcessor processor, Int32[] indeces)
   at PanCardView.CardsView.SetupNextView(Boolean canResetContext)
   at PanCardView.CardsView.SetupBackViews()
   at PanCardView.CardsView.<SetCurrentView>d__210.MoveNext()
```

**Comment by AndreiMisiukevich** [comment]
Do screens use the same bindingContext?

**Comment by JTOne123** [comment]
Nope

Here is my code:

```
public async override void ViewAppeared()
{
            base.ViewAppeared();

            var items = await repository.GetAll();
            Favorites = items;
}
```

**Comment by AndreiMisiukevich** [comment]
hmm, it must be there is a bug with getting context.
So, your index is still 1, but there is only one element in the collection.

Paul, can you try to set index to 0 before changing your collection. I think it can be a workaround for you. I will figure out with this issue later. I hope it something easy

**Comment by JTOne123** [comment]
Hmm, I think so also, but it didn't help

`        protected override void OnDisappearing()
        {
            base.OnDisappearing();

            favoritesCarousel.CurrentIndex = 0;
        }
`

**Comment by AndreiMisiukevich** [comment]
if it's possible, can you create small sample that demonstrate this behavior
