### ISSUE TITLE
[UWP] Window resizing crash

### ISSUE THREAD

**Issue by JTOne123** [AndreiMisiukevich/CardView#98]
Steps to reproduce:

Version 1.6.1

1) Resize the window (a few times)

```
<cvcontrols:ParentScrollView>
                <StackLayout CompressedLayout.IsHeadless="true" Spacing="0">
                    <cvcards:CarouselView ItemsSource="{Binding ImageUrls}"
                                          HorizontalOptions="FillAndExpand"
                                          HeightRequest="313">
                        <cvcards:CarouselView.ItemTemplate>
                            <DataTemplate>
                                <ContentView>
                                    <ffimageloading:CachedImage Source="{Binding ., Converter={c:FromImageUrlConverter}}"
                                                                LoadingPlaceholder="resource://loading.png"
                                                                ErrorPlaceholder="resource://error.png"
                                                                Aspect="AspectFill"
                                                                VerticalOptions="FillAndExpand"
                                                                HorizontalOptions="FillAndExpand"
                                                                WidthRequest="500"
                                                                HeightRequest="313"
                                                                DownsampleToViewSize="true">
                                    </ffimageloading:CachedImage>
                                </ContentView>
                            </DataTemplate>
                        </cvcards:CarouselView.ItemTemplate>
                        <cvcontrols:IndicatorsControl/>
                    </cvcards:CarouselView>
</cvcontrols:ParentScrollView>
</StackLayout>
```

2) Get the crash

```
Cannot change ObservableCollection during a CollectionChanged event.

   at Xamarin.Forms.Platform.UWP.TaskExtensions.<>c.<WatchForError>b__2_1(Object e)
   at System.Threading.WinRTSynchronizationContextBase.Invoker.InvokeCore()
```

**Comment by AndreiMisiukevich** [comment]
@JTOne123 Hi. Unfortunately, I have no windows PC/Laptop..
Could you try to investigate this issue?

**Comment by JTOne123** [comment]
yes, sure

**Comment by JTOne123** [comment]
Fixed https://github.com/AndreiMisiukevich/CardView/pull/99

There are two exceptions here
1 In the adding
2 In the removing

Steps to reproduce
1 In the sample, in CarouselSampleXamlView.xaml need to set SlideShowDuration="100"
2 After that fast resize the app's window a few times

**Comment by AndreiMisiukevich** [comment]
Wow, great
I will validate the PR on this week

**Comment by AndreiMisiukevich** [comment]
@JTOne123 thanks
Will be available in next release (I'll create it tomorrow, i think, or on weekend)
